### ISSUE TITLE
Error from Numba part

### ISSUE THREAD

**Issue by Luckick** [abojchevski/node_embedding_attack#1]
Hi,

When I am running example.ipynb, it can not run successfully and the following error shows up:
`TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.typeinfer.CallConstraint object at 0x7f520ddd1f50>.
Failed in nopython mode pipeline (step: nopython mode backend)
Type of #4 arg mismatch: i1 != i32`

When I comment all the numba.jit out, it runs and I get the same result as ipynb shows.

Is this due to package version? How can I use numba correctly?
Thanks!

Version of my packages are:
numba: '0.46.0'
numpy: '1.17.4'

**Comment by abojchevski** [comment]
Hi,

I just updated my versions of the packages to match yours. I am still able to successfully run the entire code without any errors. 

Can you please specify for which function do you get the error since I use numba for multiple functions?

As an alternative, you can comment out the `@numba.jit(nopython=True)` annotation on the respective function and the code should still work, however it will run significantly slower.

**Comment by Luckick** [comment]
It fails at every numba, except one function that was never called.
`@numba.jit(nopython=True)
def estimate_delta_eigenvecs(candidates, flip_indicator, degrees, vals_org, vecs_org, delta_eigvals, pinvs):`

Here are more versions of my packages.
scipy: '1.3.2'
Ubuntu 16.04.5 LTS

**Comment by abojchevski** [comment]
I updated my version of scipy to match yours but I am still not able to reproduce the bug. 

My OS is also Ubuntu `16.04.6 LTS` 

Which version of Python are you running? I tested the code on `3.8.0`, `3.7.5`, and `3.7.3` and it works on all three.

I am using `conda` to manage my environments.

**Comment by Luckick** [comment]
I am using Python 3.7.5 (default, Oct 25 2019, 15:51:11) and also conda.
This is weird, but anyway the code still runs without numba.

Thank you!
